import type { Metadata } from "next";
import Link from "next/link";
import { Heart, Users, DollarSign, Award, CheckCircle } from "lucide-react";

export const metadata: Metadata = {
  title: "Fundraising & Community | Abraham's Table",
  description: "Host your organization's fundraising event with Abraham's Table. We donate 20% of sales back to local schools and causes.",
};

export default function FundraisingPage() {
  return (
    <main className="min-h-screen bg-[#fdfbf7]">
      {/* Hero Banner */}
      <div className="w-full bg-gradient-to-br from-[#451400] via-[#5a1e08] to-[#451400] text-white py-16 px-6 text-center">
        <div className="max-w-4xl mx-auto">
          <span className="inline-block bg-amber-400/20 text-amber-300 text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full mb-3">
            Community Giving Back
          </span>
          <h1
            className="text-4xl md:text-6xl font-bold uppercase tracking-wider mb-4"
            style={{ fontFamily: "var(--font-anton)" }}
          >
            Fundraising With Abraham&apos;s Table
          </h1>
          <p className="text-amber-100/80 text-base md:text-lg max-w-2xl mx-auto font-medium leading-relaxed">
            We love supporting local schools, sports teams, non-profits, and community causes. Host a fundraising night with us and we&apos;ll donate <strong>20% of event sales</strong> back to your organization!
          </p>
        </div>
      </div>

      {/* How it works */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-14">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-[#451400] uppercase" style={{ fontFamily: "var(--font-anton)" }}>
            How Our Fundraising Night Works
          </h2>
          <p className="text-gray-600 text-sm mt-1">3 simple steps to raise funds for your cause</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <div className="bg-white p-6 rounded-2xl border border-amber-900/10 shadow-xs text-center">
            <div className="w-14 h-14 bg-[#451400]/10 text-[#451400] rounded-full flex items-center justify-center mx-auto mb-4 font-bold text-xl">
              1
            </div>
            <h3 className="font-bold text-[#451400] uppercase text-lg mb-2" style={{ fontFamily: "var(--font-anton)" }}>
              Request a Date
            </h3>
            <p className="text-gray-600 text-xs leading-relaxed">
              Submit your organization details and pick a preferred weekday evening at any of our Lahore branches.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-amber-900/10 shadow-xs text-center">
            <div className="w-14 h-14 bg-[#a32a22]/10 text-[#a32a22] rounded-full flex items-center justify-center mx-auto mb-4 font-bold text-xl">
              2
            </div>
            <h3 className="font-bold text-[#451400] uppercase text-lg mb-2" style={{ fontFamily: "var(--font-anton)" }}>
              Spread the Word
            </h3>
            <p className="text-gray-600 text-xs leading-relaxed">
              We provide digital flyers and promo codes. Invite your supporters, friends, and family to order or dine-in.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-amber-900/10 shadow-xs text-center">
            <div className="w-14 h-14 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center mx-auto mb-4 font-bold text-xl">
              3
            </div>
            <h3 className="font-bold text-[#451400] uppercase text-lg mb-2" style={{ fontFamily: "var(--font-anton)" }}>
              Receive Your Check
            </h3>
            <p className="text-gray-600 text-xs leading-relaxed">
              We donate 20% of all tracked dine-in, pickup, and online orders generated by your supporters!
            </p>
          </div>
        </div>

        {/* Contact CTA card */}
        <div className="bg-white rounded-2xl p-8 border border-amber-900/10 shadow-sm flex flex-col md:flex-row items-center justify-between gap-6">
          <div>
            <h3 className="text-2xl font-bold text-[#451400] uppercase" style={{ fontFamily: "var(--font-anton)" }}>
              Ready to Host an Event?
            </h3>
            <p className="text-gray-600 text-sm mt-1">
              Reach out to our Community Relations manager or drop us a line at <strong>0335-8746804</strong>.
            </p>
          </div>
          <Link
            href="/contact"
            className="shrink-0 bg-[#a32a22] text-white px-8 py-3 rounded-lg text-sm font-bold uppercase tracking-wider hover:bg-[#7a2e15] transition-colors"
            style={{ fontFamily: "var(--font-anton)" }}
          >
            Apply for Fundraiser
          </Link>
        </div>
      </div>
    </main>
  );
}
